version: 2.1
jobs:

  build_docker:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t boostpow-cpuminer . 
      - run:
          name: Push to Docker Hub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
            docker tag boostpow-cpuminer proofofwork/boostpow-cpuminer:$CIRCLE_BRANCH
            docker push proofofwork/boostpow-cpuminer:$CIRCLE_BRANCH


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker
